version: "3.9"

services:
  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - wordpress_vol:/var/www/html
    restart: on-failure
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "https://localhost/healthcheck"]
    #   interval: 30s
    #   retries: 3
    #   timeout: 10s
    #   start_period: 10s
    networks:
      - diggens

  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    ports:
      - "3306:3306"
    volumes:
      - mariadb_vol:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=wordpress
      - MARIADB_USER=wordpress
      - MARIADB_PASSWORD=wordpress
    restart: on-failure
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 30s
      retries: 3
      timeout: 10s
    networks:
      - diggens

  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    container_name: wordpress
    depends_on:
      mariadb:
        condition: service_healthy
    ports:
      - "9000:9000"
    volumes:
      - wordpress_vol:/var/www/html
    environment:
      - WORDPRESS_DB_HOST=mariadb
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
    restart: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/"]
      interval: 30s
      retries: 3
      timeout: 10s
      start_period: 10s
    networks:
      - diggens

volumes:
    mariadb_vol:
      driver: local
    wordpress_vol:
      driver: local

networks:
  diggens:
    driver: bridge
