services:
  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    image: nginx
    depends_on:
      - wordpress
    env_file:
      - ../secrets/.env
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./data/wordpress_vol:/var/www/html
      - ./requirements/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
    restart: on-failure
    networks:
      - diggens

  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    image: mariadb
    env_file:
      - ../secrets/.env
    volumes:
      - ./data/mariadb_vol:/var/lib/mysql
    restart: on-failure
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot_password", "--silent"]
      interval: 30s
      retries: 3
      timeout: 10s
    networks:
      - diggens

  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    container_name: wordpress
    image: wordpress
    depends_on:
      - mariadb
    env_file:
      - ../secrets/.env
    volumes:
      - ./data/wordpress_vol:/var/www/html
    restart: on-failure
    healthcheck:
      test: ["CMD", "bash", "-c", "nc -z localhost 9000 || exit 1"]
      interval: 33s
      retries: 5
      timeout: 10s
      start_period: 20s
    networks:
      - diggens

# volumes:
#     mariadb_vol:
#       name: mariadb_vol
#       driver: local
#       driver_opts:
#         type: none
#         o: bind
#         device: /Users/fwahl/code/Inception/data/maria_db
#     wordpress_vol:
#       name: wordpress_vol
#       driver: local
#       driver_opts:
#         type: none
#         o: bind
#         device: /Users/fwahl/code/Inception/data/wordpress

networks:
  diggens:
    name: diggens
    driver: bridge
