services:
  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    image: nginx
    depends_on:
      - wordpress
    environment:
      WP_URL: https://localhost
      WP_TITLE: Inception
      WP_ADMIN_USER: admin
      WP_ADMIN_EMAIL: abc@gmail.com
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./data/wordpress_vol:/var/www/html
      - ./requirements/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
    restart: on-failure
    networks:
      - diggens

  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    image: mariadb
    environment:
      DB_HOST: mariadb
      DB_DATABASE: wordpress
      DB_USER: wp_user
    secrets:
      - db_root_password
      - db_user_password
    volumes:
      - ./data/mariadb_vol:/var/lib/mysql
    restart: on-failure
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot_password", "--silent"]
      interval: 30s
      retries: 3
      timeout: 10s
    networks:
      - diggens

  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    container_name: wordpress
    image: wordpress
    depends_on:
      - mariadb
    environment:
      DB_HOST: mariadb
      DB_DATABASE: wordpress
      DB_USER: wp_user
      WP_URL: https://localhost
      WP_TITLE: Inception
      WP_ADMIN_USER: wp_admin
      WP_ADMIN_EMAIL: wp_admin@gmail.com
    secrets:
      - db_user_password
      - wp_admin_password
    volumes:
      - ./data/wordpress_vol:/var/www/html
    restart: on-failure
    healthcheck:
      test: ["CMD", "pgrep", "-x", "php-fpm7.4"]
      interval: 33s
      retries: 5
      timeout: 10s
      start_period: 20s
    networks:
      - diggens

secrets:
  db_root_password:
    file: ../secrets/db_root_password
  db_user_password:
    file: ../secrets/db_user_password
  wp_admin_password:
    file: ../secrets/wp_admin_password

networks:
  diggens:
    name: diggens
    driver: bridge

# volumes:
#     mariadb_vol:
#       name: mariadb_vol
#       driver: local
#       driver_opts:
#         type: none
#         o: bind
#         device: /Users/fwahl/code/Inception/data/maria_db
#     wordpress_vol:
#       name: wordpress_vol
#       driver: local
#       driver_opts:
#         type: none
#         o: bind
#         device: /Users/fwahl/code/Inception/data/wordpress
