version: "3.9"

services:
  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    # depends_on:
    #   - wordpress
    ports:
      - "443:443"
    # volumes:
    #   - ./requirements/nginx/conf:/etc/nginx/conf.d
    volumes:
      - ./wordpress_vol:/var/www/html
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "https://localhost/healthcheck"]
      interval: 30s
      retries: 3
      timeout: 10s
      start_period: 10s

  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    ports:
      - "3306:3306"
    volumes:
      - mariadb_vol:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=wordpress
      - MARIADB_USER=wordpress
      - MARIADB_PASSWORD=wordpress
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 30s
      retries: 3
      timeout: 10s


#   wordpress:
#     build:
#       context: ./requirements/wordpress
#       dockerfile: Dockerfile
#     container_name: wordpress
#     ports:
#       - "9000:9000"
#     volumes:
#       - wordpress_vol:/var/www/html
#     environment:
#       - WORDPRESS_DB_HOST=localhost  #update when adding MariaDB
#       - WORDPRESS_DB_NAME=wordpress
#       - WORDPRESS_DB_USER=root
#       - WORDPRESS_DB_PASSWORD=root_password  # Change as needed
#     restart: always
#     healthcheck:
#       test: ["CMD", "curl", "-f", "http://localhost:9000/"]
#       interval: 30s
#       retries: 3
#       timeout: 10s
#       start_period: 10s

volumes:
    mariadb_vol:
      driver: local

#   wordpress_data:
#     driver: local
